# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'du_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_du_Ui(object):
    def setupUi(self, du_Ui):
        du_Ui.setObjectName(_fromUtf8("du_Ui"))
        du_Ui.resize(364, 452)
        self.centralwidget = QtGui.QWidget(du_Ui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 361, 451))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.toolBox = QtGui.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(2, 62, 351, 321))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 351, 269))
        self.page.setObjectName(_fromUtf8("page"))
        self.textEdit = QtGui.QTextEdit(self.page)
        self.textEdit.setGeometry(QtCore.QRect(0, -2, 351, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(0, 317, 350, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 351, 269))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.lineEdit = QtGui.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 248, 350, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 351, 241))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(5, 1, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(122, 22, 200, 16))
        self.horizontalSlider_2.setMaximum(9)
        self.horizontalSlider_2.setProperty("value", 5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(82, 2, 36, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(82, 38, 36, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(331, 2, 20, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalSlider = QtGui.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(122, 3, 200, 16))
        self.horizontalSlider.setMaximum(9)
        self.horizontalSlider.setProperty("value", 5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(331, 20, 20, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(331, 38, 20, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(6, 32, 70, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(82, 20, 36, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalSlider_3 = QtGui.QSlider(self.tab)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(122, 40, 200, 16))
        self.horizontalSlider_3.setMaximum(15)
        self.horizontalSlider_3.setProperty("value", 5)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(210, 391, 75, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 391, 75, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 291, 321))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        du_Ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(du_Ui)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(du_Ui)

    def retranslateUi(self, du_Ui):
        du_Ui.setWindowTitle(_translate("du_Ui", "XTTS by Eastlovsky", None))
        self.label_7.setText(_translate("du_Ui", "duinfo", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("du_Ui", "文字转语音", None))
        self.label_2.setText(_translate("du_Ui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("du_Ui", "表情文字提取转语音", None))
        self.label_3.setText(_translate("du_Ui", "讲话人：", None))
        self.label_4.setText(_translate("du_Ui", "语速：", None))
        self.label_6.setText(_translate("du_Ui", "音量：", None))
        self.label_8.setText(_translate("du_Ui", "5", None))
        self.label_9.setText(_translate("du_Ui", "5", None))
        self.label_10.setText(_translate("du_Ui", "5", None))
        self.comboBox.setItemText(0, _translate("du_Ui", "标准女", None))
        self.comboBox.setItemText(1, _translate("du_Ui", "标准男", None))
        self.comboBox.setItemText(2, _translate("du_Ui", "-------", None))
        self.comboBox.setItemText(3, _translate("du_Ui", "度逍遥", None))
        self.comboBox.setItemText(4, _translate("du_Ui", "度丫丫", None))
        self.label_5.setText(_translate("du_Ui", "语调：", None))
        self.pushButton.setText(_translate("du_Ui", "再说一次", None))
        self.pushButton_3.setText(_translate("du_Ui", "重新识别", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("du_Ui", "操作区", None))
        self.label.setText(_translate("du_Ui", "<html><head/><body><p><span style=\" font-size:10pt;\">声明：感谢以下技术</span></p><p><span style=\" font-size:10pt;\">Python v2.7.14</span></p><p><span style=\" font-size:10pt;\">百度大脑（图文识别）baidu-aip v1.6.6.0</span></p><p>PYQT v4.11.4</p><p>pypinyin v0.25.0</p><p>PIL v1.1.7</p><p>playsound v1.2.2</p><p>PyInstaller v3.3</p><p><br/></p><p><span style=\" font-size:10pt;\"><br/>作者：Eastlovsky</span></p><p><span style=\" font-size:10pt;\">软件用户QQ群：</span><a href=\"https://jq.qq.com/?_wv=1027&amp;k=53cjppp\"><span style=\" text-decoration: underline; color:#0000ff;\">490341642</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("du_Ui", "作者声明", None))

